### PR TITLE
Added tabbing for the labels. Fixing #17

### PR DESCRIPTION
**Pull request by terhechte**
This includes tabbing functionality for navigating the labels.

### CODE REVIEW

**Comment by PanosSakkos** [comment]
Great stuff @terhechte ! 

That means we are one issue away from using Dono only with the keyboard! :clap:

**Comment by Stankec** [comment]
Hey! @terhechte can you remove the `print(self.labels.count())`? We'll merge this then.

**Comment by terhechte** [comment]
Just removed the print :-)

**Comment by Stankec** [comment]
Thanks

**Pull request merged**
